import logging
import re
from typing import List, Dict, Any
from datetime import datetime, timezone
import math

logger = logging.getLogger(__name__)

def generate_committee_analysis(symbol: str, name: str) -> Dict[str, Any]:
    """
    Simulates a detailed, interactive multi-agent debate for a given Indian stock.
    Returns transcript steps and a synthesized scorecard.
    """
    sym = symbol.upper()
    n = name or sym

    # Structured mock analysis based on stock category
    is_growth = sym in ["INFY", "INFY.NS", "WIPRO", "WIPRO.NS", "TCS", "TCS.NS"]
    is_resource = sym in ["NMDC", "NMDC.NS", "NTPC", "NTPC.NS", "IOC", "IOC.NS", "BPCL", "BPCL.NS"]
    
    if is_growth:
        pe_status = "moderate to high at 26.4x"
        roe_status = "healthy at 22.8%"
        tech_trend = "trading near its 50 DMA, showing consolidation pattern"
        news_sentiment = "positive corporate earnings outlook, focus on global cloud expansions"
        consensus_score = 78
        consensus_label = "ACCUMULATE"
    elif is_resource:
        pe_status = "low to moderate at 14.2x with high dividend yield support"
        roe_status = "stable at 16.5% driven by capital allocation"
        tech_trend = "bullish momentum above 200 DMA, supported by volume breakouts"
        news_sentiment = "highly positive following recent bonus issue announcements and policy tailwinds"
        consensus_score = 82
        consensus_label = "STRONG BUY"
    else:
        pe_status = "undetermined or volatile valuation multiples"
        roe_status = "moderate at 12.4%"
        tech_trend = "sideways movement inside a tight bollinger band squeeze"
        news_sentiment = "neutral with standard market interest fluctuations"
        consensus_score = 65
        consensus_label = "HOLD / NEUTRAL"

    debate_transcript = [
        {
            "agent": "Fundamental Analyst",
            "avatar": "💼",
            "role": "Value & Ratios Expert",
            "message": f"Looking at {n} ({sym}), the financials show a P/E of {pe_status} and ROE of {roe_status}. Capital structures are solid, and the return profile remains robust relative to industry peers."
        },
        {
            "agent": "Technical Analyst",
            "avatar": "📈",
            "role": "Momentum & Chart Expert",
            "message": f"From a price action standpoint, {sym} is {tech_trend}. Short-term RSI is around 54, indicating no immediate overbought conditions. Support levels are holding strong."
        },
        {
            "agent": "Sentiment Analyst",
            "avatar": "📰",
            "role": "Macro & News Scraper",
            "message": f"Recent sentiment indexes scan extremely {news_sentiment}. Social chatter and broker target consensus show rising retail and DII interest over the last month."
        },
        {
            "agent": "Committee Chair",
            "avatar": "⚖️",
            "role": "Synthesizer & Compliance Manager",
            "message": f"Summarizing the findings: Fundamental stability matches the stable momentum. We recommend a score of {consensus_score}/100 with an overall {consensus_label} outlook for research purposes."
        }
    ]

    return {
        "symbol": sym,
        "name": n,
        "score": consensus_score,
        "outlook": consensus_label,
        "debate": debate_transcript,
        "analyzed_at": datetime.now(timezone.utc).isoformat(),
        "disclaimer": "InvestMitra is NOT a SEBI-registered advisor. This analysis is generated by automated agents for educational purposes only."
    }

def parse_natural_language_backtest(prompt: str) -> Dict[str, Any]:
    """
    Parses a plain-English trading strategy prompt and maps it to simulated strategy configurations.
    """
    p_lower = prompt.lower()
    
    # Defaults
    strategy_id = "custom_agent_strategy"
    strategy_name = "AI Parsed Strategy"
    strategy_desc = "Dynamically configured trading model based on natural language query."
    
    if "ema" in p_lower or "exponential" in p_lower:
        strategy_id = "ema_crossover"
        strategy_name = "EMA Crossover Strategy"
        strategy_desc = "Trades the crossover of fast and slow Exponential Moving Averages."
    elif "rsi" in p_lower or "relative strength" in p_lower:
        strategy_id = "rsi_mean_reversion"
        strategy_name = "RSI Mean Reversion"
        strategy_desc = "Buys oversold RSI boundaries (<30) and sells overbought (>70)."
    elif "breakout" in p_lower or "bollinger" in p_lower or "volume" in p_lower:
        strategy_id = "momentum_breakout"
        strategy_name = "Momentum Volume Breakout"
        strategy_desc = "Buys when price breaks above recent highs on above-average volume."
    
    # Parse numbers if present (e.g. 20, 50, 200)
    numbers = [int(s) for s in re.findall(r'\b\d+\b', prompt)]
    if len(numbers) >= 2:
        strategy_desc += f" Parameters parsed: Fast period = {numbers[0]}, Slow period = {numbers[1]}."
    elif len(numbers) == 1:
        strategy_desc += f" Primary parameter parsed: Period = {numbers[0]}."

    return {
        "parsed": True,
        "strategy_id": strategy_id,
        "name": strategy_name,
        "description": strategy_desc,
        "original_prompt": prompt
    }

def calculate_risk_mandates(holdings: List[Dict], stock_data: Dict) -> Dict[str, Any]:
    """
    Calculates portfolio diversification (HHI index) and allocation mandate guard rails.
    """
    if not holdings:
        return {
            "hhi_index": 0.0,
            "diversification_status": "No Holdings",
            "concentration_alerts": [],
            "asset_allocation": {"STOCKS": 0.0, "MUTUAL_FUNDS": 0.0}
        }

    # Calculate total current value
    total_val = 0.0
    holding_values = []
    asset_types = {"STOCKS": 0.0, "MUTUAL_FUNDS": 0.0}

    for h in holdings:
        qty = float(h.get("quantity", 0))
        price = float(h.get("current_price", h.get("purchase_price", 0)) or 0)
        val = qty * price
        total_val += val
        
        symbol = h.get("symbol") or h.get("scheme_code") or "Unknown"
        holding_values.append({"symbol": symbol, "value": val})

        if h.get("asset_type") == "MUTUAL_FUND":
            asset_types["MUTUAL_FUNDS"] += val
        else:
            asset_types["STOCKS"] += val

    concentration_alerts = []
    hhi = 0.0

    if total_val > 0:
        for item in holding_values:
            weight = item["value"] / total_val
            hhi += (weight ** 2)
            
            # Mandate threshold alert: single stock > 25% allocation
            if weight > 0.25:
                concentration_alerts.append({
                    "symbol": item["symbol"],
                    "allocation_percent": round(weight * 100, 1),
                    "type": "SINGLE_STOCK_EXCESSIVE",
                    "message": f"{item['symbol']} accounts for {round(weight * 100, 1)}% of your portfolio, exceeding the 25% safety mandate."
                })
        
        # Format allocation percentages
        asset_types["STOCKS"] = round((asset_types["STOCKS"] / total_val) * 100, 1)
        asset_types["MUTUAL_FUNDS"] = round((asset_types["MUTUAL_FUNDS"] / total_val) * 100, 1)
    
    # HHI Classification
    if hhi < 0.15:
        div_status = "Well Diversified (Safe)"
        div_color = "text-emerald-400"
    elif hhi <= 0.25:
        div_status = "Moderately Concentrated"
        div_color = "text-amber-400"
    else:
        div_status = "Highly Concentrated (Risky)"
        div_color = "text-rose-400"

    return {
        "hhi_index": round(hhi, 3),
        "diversification_status": div_status,
        "diversification_color": div_color,
        "concentration_alerts": concentration_alerts,
        "asset_allocation": asset_types,
        "total_value": round(total_val, 2)
    }

def generate_portfolio_diagnostics(holdings: List[Dict], transactions: List[Dict]) -> List[Dict[str, Any]]:
    """
    Scans holdings and transaction logs to diagnose behavioral patterns (e.g. Averaging Down, Falling Knives).
    """
    diagnostics = []
    
    # 1. Look for Averaging Down behavior
    # Group transactions by symbol
    buy_txns = [t for t in transactions if str(t.get("transaction_type") or t.get("type")).lower() == "buy"]
    symbol_buys = {}
    for t in buy_txns:
        sym = t.get("symbol")
        if sym:
            symbol_buys.setdefault(sym, []).append(t)
            
    for sym, txns in symbol_buys.items():
        if len(txns) >= 2:
            # Sort by date
            sorted_txns = sorted(txns, key=lambda x: x.get("transaction_date") or x.get("date") or "")
            first_buy = sorted_txns[0]
            last_buy = sorted_txns[-1]
            
            f_price = float(first_buy.get("price", 0))
            l_price = float(last_buy.get("price", 0))
            
            if l_price < f_price and l_price > 0:
                diagnostics.append({
                    "symbol": sym,
                    "type": "SMART_AVERAGING",
                    "title": "Tactical Cost-Averaging",
                    "severity": "info",
                    "message": f"You successfully averaged down {sym} by acquiring additional shares at a lower cost (from ₹{f_price:.2f} down to ₹{l_price:.2f}). This reduced your breakeven threshold."
                })

    # 2. Check for Portfolio Concentration warning
    if len(holdings) > 0:
        total_qty = sum(float(h.get("quantity", 0)) for h in holdings)
        for h in holdings:
            qty = float(h.get("quantity", 0))
            if total_qty > 0 and (qty / total_qty) > 0.4:
                diagnostics.append({
                    "symbol": h.get("symbol") or h.get("scheme_code"),
                    "type": "CONCENTRATION_RISK",
                    "title": "Overweight Allocation",
                    "severity": "warning",
                    "message": f"Your position in {h.get('symbol') or h.get('scheme_code')} represents over 40% of your total holding units. Consider balancing into other sectors to reduce volatility."
                })

    # 3. Add a default healthy holding diagnosis if nothing else is flagged
    if not diagnostics:
        diagnostics.append({
            "symbol": "General",
            "type": "HEALTHY",
            "title": "Consistent Capital Allocation",
            "severity": "success",
            "message": "Your portfolio shows structured allocations with clear cost parameters. Keep tracking your entry dates for corporate action alignment."
        })

    return diagnostics
